### ISSUE TITLE
Support GHC 9.6.3

### ISSUE THREAD

**Issue by mpilgrem** [benz0li/ghc-musl#5]
GHC 9.6.3 is not in the Version Matrix but is now supported by `nightly-2023-10-01`.

GHC 9.6.3 has an 'official' Alpine Linux/x86_64 version (dynamically linked) that, I think, is free of the problems that trouble the statically-linked versions for that platform.

Also, Stack 2.13.1 has been released. All of its 'official' Linux binary distributions are now statically linked.

**Comment by benz0li** [comment]
> GHC 9.6.3 is not in the Version Matrix but is now supported by `nightly-2023-10-01`.

`glcr.b-data.ch/ghc/ghc-musl:9.6.3` will be available by tonight.

> GHC 9.6.3 has an 'official' Alpine Linux/x86_64 version (dynamically linked) that, I think, is free of the problems that trouble the statically-linked versions for that platform.

As long as there is no GHC binary distribution for Alpine Linux/AArch64 available, the images will created as follows:

1. Multi‑arch: `linux/amd64`, `linux/arm64/v8`
1. Built using Hadrian, from source, without docs
1. Built using the LLVM backend
    * flavour: `perf+llvm+split_sections`

> Also, Stack 2.13.1 has been released. All of its 'official' Linux binary distributions are now statically linked.

That is great news! Stack 2.13.1 will be part of

* `glcr.b-data.ch/ghc/ghc-musl:9.6.3`
* `glcr.b-data.ch/ghc/ghc-musl:9.4.7`
* `glcr.b-data.ch/ghc/ghc-musl:9.2.8`

**Comment by benz0li** [comment]
@mpilgrem I will create a pull request for Stack's Dev Containers as soon as everything is ready.

**Comment by benz0li** [comment]
> @mpilgrem I will create a pull request for Stack's Dev Containers as soon as everything is ready.

Done.

Cross reference: https://github.com/commercialhaskell/stack/pull/6266
