### ISSUE TITLE
GHC tarball stored in intermediate docker layer

### ISSUE THREAD

**Issue by bjin** [benz0li/ghc-musl#6]
The compiled GHC tarball is stored in an intermediate layer in`/tmp` before extracted and deleted. Therefore, the size of the tarball (roughly 200MB) still counts to the size of final image, and made the image significantly larger and difficult to fetch. See

https://github.com/benz0li/ghc-musl/blob/8dcfea340cfe3f2efc86f36ebb91599f05761c24/latest.Dockerfile#L119-L123

To shrink the size of final docker image, we could

* Squash the final image, with something like 
```dockerfile
FROM scratch
COPY --from=ghc-stage1 / /
COPY --from=ghc-stage2 /root/.local/bin/cabal /usr/local/bin/cabal
CMD ["ghci"]
```
* use `COPY --link` for tarball copying

**Comment by benz0li** [comment]
@bjin You are right.

I will look into it asap and rebuild smaller images for GHC versions 9.8.1, 9.6.4, 9.4.8 and 9.2.8.

**Comment by benz0li** [comment]
`glcr.b-data.ch/ghc/ghc-musl:9.8.1` is currently rebuilding: https://gitlab.b-data.ch/ghc/ghc-musl/-/pipelines/25874

`glcr.b-data.ch/ghc/ghc-musl:9.6.4` and `glcr.b-data.ch/ghc/ghc-musl:9.4.8` will be available until this evening.

**Comment by benz0li** [comment]
`glcr.b-data.ch/ghc/ghc-musl:9.8.1` is ready.

---

Reduction of image size (compressed):

* `linux/amd64`: 801.69 MiB - 598.06 MiB = 203.63 MiB (25.4%)
* `linux/amd64/v8`: 849.41 MiB - 640.75 MiB = 208.66 MiB (24.6%)

**Comment by benz0li** [comment]
`glcr.b-data.ch/ghc/ghc-musl:9.2.8` has also been rebuilt.
