### ISSUE TITLE
ghc 9.6.5 and stack 2.15.7

### ISSUE THREAD

**Issue by bjin** [benz0li/ghc-musl#7]
[ghc 9.6.5](https://www.haskell.org/ghc/blog/20240416-ghc-9.6.5-released.html) and [stack 2.15.7](https://github.com/commercialhaskell/stack/releases/tag/v2.15.7) are out. Could you please build image for them? Latest stackage lts is already using `ghc 9.6.5`.

**Comment by benz0li** [comment]
@bjin An image including GHC v9.6.5 + Stack v2.15.5 is already available: https://github.com/benz0li/ghc-musl/commit/8753dc285dd0361446c40fd8be0df0cc5d904c07

I will rebuild with Stack v2.15.7 shortly.

**Comment by benz0li** [comment]
@bjin Done. The GHC v9.6.5 image now includes Stack v2.15.7.
